### ISSUE TITLE
【求解答】Command#command() 是否可以不设置呢？

### ISSUE THREAD

**Issue by Vizards** [jaywcjlove/wcj#2]
比如，我现在需要将一个 node.js 程序 xxx-spider.js 制作成命令行工具，在npm install -g 之后便可以在命令行中调用这个程序

```
xxx-spider  [options]
```

如果使用了Command.js 中的 `program.command('commander')` , 那么程序在执行的时候就需要这样：

```
xxx-spider commander [options]
```

有什么方法可以去掉这个`commander`参数呢，让使用了 Command.js 的 NodeJS 程序可以直接 `xxx-spider [options]` ？直接去掉会导致程序不执行，官方的 API 也没有提及此问题，希望能给予解答。

**Comment by jaywcjlove** [comment]
```
program.command('commander')
```
你自己定义的命令`commander`，这个改成你想要的不就行了？
好好看官方文档哦

**Comment by Vizards** [comment]
假设我定义commander 为 `xxx-spider` 了之后，执行时仍然需要 `xxx-spider xxx-spider [options]` ，相当于第一个xxx-spider是调用了js，第二个xxx-spider调用了 commander 里的命令，而我希望的是直接 `xxx-spider [options]`，这该怎么做呢？

**Comment by Vizards** [comment]
也即您文档里使用的例子：
```
./bin/wcj.js resume ss -n aaaaa
```

当您把 wcj.js 制作成命令行工具之后，执行此命令仍然需要 `wcj resume ss -n aaa` 
我现在不需要 resume 这个 commander ，希望能直接执行 `wcj -n aaa`, 该如何修改呢？

**Comment by jaywcjlove** [comment]
@Vizards

文档没有好好看，下面是我两个小例子源码，我都不知道你的代码是咋写的呢，

你可以把例子 下载下来，运行一下，看一下哦。

[编写命令行](https://github.com/jaywcjlove/wcj#编写命令行)  
[一个小列子源码](https://github.com/jaywcjlove/wcj/blob/master/examples/ls.js)
